config/routes.rb
Helloworld::Application.routes.draw do
  match 'about' => 'posts#about'

  resources :posts, :path => "/"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body

  # validate new posts
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		order = params[:sort]
		order = 'created_at' if order != 'votes'
		@posts = Post.find(:all, :order => order + ' DESC')
		@title = "Hello, world"
	end

	def new
		@post = Post.new
		@title = "Hello, world - write"
	end

	def create
		# save post info from form into a post object
		# initialize the number of votes and flags to 0
		@post = Post.new(params[:post])
		@post.votes = 0
		@post.flagged = 0
		if @post.save
			# redirect to the posts index (which is routed to the root index)
			redirect_to posts_url
		else
			render :action => "new"
		end
	end

	def show
		# get the ID of the post
		id = params[:id]
		# find the post by its ID
		@post = Post.find(id)
	end

	# associated with the PUT action
	# so when we hit this url with a PUT request, this will run
	def update
		# find our post
		id = params[:id]
		@post = Post.find(id)

		# increment the number of votes
		if params[:tweet] == "true"
			@post.votes = @post.votes + 1
			@post.save
		elsif params[:flagged] == "true"
			@post.flagged = @post.flagged + 1
			@post.save
		end
		
		# TODO: ask Tom what this does again
		render :json => @post
	end

	def about
		@title = "Hello, world - about"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="header">
	<div>
		<%= link_to "read", :controller => "posts", :action => "index" %>
		<%= link_to "write", :controller => "posts", :action => "new" %>
		<%= link_to "about", :controller => "posts", :action => "about" %>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/posts/about.html.erb
<div id="wrapper">
	<div id="column-left">
		What is this website?
	</div>

	<div id="column-right">
		<p>One day, I read <a href="http://www.women2.com/why-women-dont-code/" title="http://www.women2.com/why-women-dont-code/">this article</a> and started thinking about my own experiences with learning to code. I tweeted the following:</p>

		<blockquote><div>&ldquo;</div>What are your thoughts on high "getting started" costs as a barrier to learning programming? Especially for those trying to self-teach.</blockquote>

		<p>While I had been thinking of specific problems I'd personally faced, the diversity of the responses really surprised me. I realized that there were a lot of problems people were running into that weren't getting talked about, and that there were lots of eager beginners who were giving up because they had been told that their problems weren't worth acknowledging.</p>

		<p>So, I made this app. The goal is to create a place where people can share the challenges they've run into, so that everyone can see what problems what people are having. My hope is that by sharing our experiences, all of us will become more aware of the barriers that beginners face and what we can do to remove them.</p>

		<p>&ndash; <a href="http://twitter.com/nkkl" title="http://twitter.com/nkkl">@nkkl</a></p>
	</div>
</div>

app/views/posts/index.html.erb
<div id="wrapper">
	<div id="column-left">
		What are your thoughts on high "getting started" costs as a barrier to learning programming?
	</div>

	<div id="column-right">
		<% for post in @posts %>
			<div class="post" data-post-id="<%= post.id %>">
				<div class="post-body">
					<%= simple_format(post.body) %>
				</div>

				<div class="post-date">
					Written on <%= link_to localize(post.created_at, :format => :long), post_url(post) %>
				</div>

				<div class="post-actions">
					<div class="flag">flag</div> <a href="https://twitter.com/share?url=<%= post_url(post) %>" class="twitter-share-button" data-text=" " data-lang="en">Tweet</a>
				</div>
			</div>
		<% end %>

		<%= link_to "Add your own story!", {:controller => "posts", :action => "new"}, { :class => "button" } %>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	// First, load the widgets.js file asynchronously 
	window.twttr = (function (d,s,id) {
		var t, js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
		js.src="//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
		return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
	}(document, "script", "twitter-wjs"));
 
	// Wait for the asynchronous resources to load
	twttr.ready(function (twttr) {
		// bind a tweet-button-click action to a callback
		twttr.events.bind("tweet", function(intent_event) {
			// grab the post ID from the intent_event
			var id = $(intent_event.target).parent().parent().attr("data-post-id");
			// use AJAX to hit the posts_url with a PUT request
			$.ajax("<%= posts_url %>" + id, {
				type: "PUT",
				data: { "tweet": true,
						"flagged": false }
			}).done(function() {
			});
		});
	});

	$(".flag").click(function() {
		if ($(this).hasClass("clicked")) {
			$(this).toggleClass("clicked");
			var id = $(this).parent().parent().attr("data-post-id");
			$.ajax("<%= posts_url %>" + id, {
					type: "PUT",
					data: { "tweet": false,
							"flagged": true }
				}).done(function() {});
		} else {
			$(this).toggleClass("clicked");
		}
	});
</script>

app/views/posts/new.html.erb
<div id="wrapper">
	<div id="column-left">
		What are your thoughts on high "getting started" costs as a barrier to learning programming?
	</div>	
	
	<div id="column-right">	
		<%= form_for @post, :url => { :action => "create" } do |f| %>
			<% @post.errors.full_messages.each do |msg| %>
		      <p><%= msg %></p>
		    <% end %>
			<%= f.text_area :body %>
			<%= f.submit "submit" %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div id="wrapper">
	<div id="column-left">
		What are your thoughts on high "getting started" costs as a barrier to learning programming?
	</div>

	<div id="column-right">
		<div class="post-body">
			<%= simple_format(@post.body) %>
		</div>

		<div class="post-date">
			Written on <%= localize(@post.created_at, :format => :long) %><br>
			<%= link_to "« back", posts_url %>
		</div>

		<div class="post-actions">
			<div class="flag">flag</div> <a href="https://twitter.com/share?url=<%= post_url(@post) %>" class="twitter-share-button" data-text=" " data-lang="en">Tweet</a>
		</div>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	// First, load the widgets.js file asynchronously 
	window.twttr = (function (d,s,id) {
		var t, js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
		js.src="//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
		return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
	}(document, "script", "twitter-wjs"));
 
	// Wait for the asynchronous resources to load
	twttr.ready(function (twttr) {
		// bind a tweet-button-click action to a callback
		twttr.events.bind("tweet", function(intent_event) {
			// grab the post ID from the intent_event
			var id = $(intent_event.target).parent().parent().attr("data-post-id");
			// use AJAX to hit the posts_url with a PUT request
			$.ajax("<%= posts_url %>" + id, {
				type: "PUT",
				data: { "tweet": true,
						"flagged": false }
			}).done(function() {
			});
		});
	});

	$(".flag").click(function() {
		if ($(this).hasClass("clicked")) {
			$(this).toggleClass("clicked");
			var id = $(this).parent().parent().attr("data-post-id");
			$.ajax("<%= posts_url %>" + id, {
					type: "PUT",
					data: { "tweet": false,
							"flagged": true }
				}).done(function() {});
		} else {
			$(this).toggleClass("clicked");
		}
	});
</script>